<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'JanMalte\JmMailService\Service\MailFactory'          => __DIR__ . '/src/Service/MailFactory.php',
  'JanMalte\JmMailService\Service\MailTransportFactory' => __DIR__ . '/src/Service/MailTransportFactory.php',
  'JanMalte\JmMailService\Service\Mail'                 => __DIR__ . '/src/Service/Mail.php',
  'JanMalte\JmMailService\Service\MailInterface'        => __DIR__ . '/src/Service/MailInterface.php',
  'JanMalte\JmMailService\Module'                       => __DIR__ . '/src/Module.php',
  'JanMalte\JmMailService\Options\ModuleFactory'        => __DIR__ . '/src/Options/ModuleFactory.php',
  'JanMalte\JmMailService\Options\MailService'          => __DIR__ . '/src/Options/MailService.php',
  'JanMalte\JmMailService\Options\Module'               => __DIR__ . '/src/Options/Module.php',
  'JanMalte\JmMailService\Options\Transport'            => __DIR__ . '/src/Options/Transport.php',
);
